version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rgap-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: rgap
      MYSQL_USER: rgap_user
      MYSQL_PASSWORD: 12345
    ports:
      - "${DB_PORT:-7272}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: rgap-server
    environment:
      - DB_HOST=mysql
      - DB_USER=rgap_user
      - DB_PASSWORD=12345
      - DB_NAME=rgap
      - DB_PORT=3306
      - PORT=${API_PORT:-3030}
    ports:
      - "${API_PORT:-3030}:3030"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rgap-client
    environment:
      - VITE_API_URL=http://localhost:${API_PORT:-3030}
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  mysql_data: