version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rgap-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: rgap
      MYSQL_USER: rgap_user
      MYSQL_PASSWORD: 12345
      DB_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
      - ./data/sample:/data/sample
    command: >
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci 
      --local-infile=1
      --port=${DB_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "rgap_user", "--password=12345", "--port=${DB_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: rgap-server
    restart: unless-stopped
    environment:
      - DB_HOST=mysql
      - DB_USER=rgap_user
      - DB_PASSWORD=12345
      - DB_NAME=rgap
      - DB_PORT=${DB_PORT}
      - PORT=${API_PORT}
      - NODE_ENV=production
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: rgap-client
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:${API_PORT}
      - PORT=${CLIENT_PORT}
      - NODE_ENV=production
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

volumes:
  mysql_data: